spring.application.name=StudioPilates

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.security.user.name=gabriel
spring.security.user.password=teste123

management.endpoints.web.exposure.include=*
#management.endpoints.web.exposure.exclude=health,info
management.info.env.enabled=true

info.app.name=Pilates Backend
info.app.description=A solution that provides API for Pilates Studio
info.app.version=1.0.0

#Use wildcard "*" to expose all endpoints
#Can also expose individual endpoints with a comma-delimited list